name: Clang Format Check

on: [ push, pull_request ]

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install clang-format
      run: sudo apt-get install clang-format

    - name: Check format
      run: |
        find . -name './src/*.cpp' -o -name './include/*.hpp' | xargs clang-format -i
        git diff --exit-code
