name: e2e Test

on: push

jobs:
  e2e:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install -y cmake python3 python3-pip &&
          pip3 install -r ./test/e2e/requirements.txt

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

      - name: Build
        run: make re

      - name: Run tests
        run: make test/e2e
