name: e2e Test

on: push

jobs:
  gtest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt-get update &&
          sudo apt-get install -y cmake python3 python3-pip &&
          pip3 install ./test/e2e/requirements.txt

      - name: Build
        run: make re

      - name: Run tests
        run: make test/e2e
