name: Google Test

on: [push, pull_request]

jobs:
  gtest:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake g++

    - name: Configure
      run: cmake -S . -B build

    - name: Build
      run: cmake --build build

    - name: Test
      run: ./build/example_test
